package com.sheshu.fluenticons.filled

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import com.sheshu.fluenticons.FluentIcons

public val FluentIcons.Filled.QrCode24: ImageVector by lazy(LazyThreadSafetyMode.NONE) {
    ImageVector.Builder(
        name = "Filled.QrCode24",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f
    ).apply {
        path(fill = SolidColor(Color.Black)) {
            moveTo(8f, 6f)
            horizontalLineTo(6f)
            verticalLineToRelative(2f)
            horizontalLineToRelative(2f)
            verticalLineTo(6f)
            close()
            moveTo(3f, 5.5f)
            curveTo(3f, 4.12f, 4.12f, 3f, 5.5f, 3f)
            horizontalLineToRelative(3f)
            curveTo(9.88f, 3f, 11f, 4.12f, 11f, 5.5f)
            verticalLineToRelative(3f)
            curveTo(11f, 9.88f, 9.88f, 11f, 8.5f, 11f)
            horizontalLineToRelative(-3f)
            curveTo(4.12f, 11f, 3f, 9.88f, 3f, 8.5f)
            verticalLineToRelative(-3f)
            close()
            moveTo(5.5f, 5f)
            curveTo(5.224f, 5f, 5f, 5.224f, 5f, 5.5f)
            verticalLineToRelative(3f)
            curveTo(5f, 8.776f, 5.224f, 9f, 5.5f, 9f)
            horizontalLineToRelative(3f)
            curveTo(8.776f, 9f, 9f, 8.776f, 9f, 8.5f)
            verticalLineToRelative(-3f)
            curveTo(9f, 5.224f, 8.776f, 5f, 8.5f, 5f)
            horizontalLineToRelative(-3f)
            close()
            moveTo(6f, 16f)
            horizontalLineToRelative(2f)
            verticalLineToRelative(2f)
            horizontalLineTo(6f)
            verticalLineToRelative(-2f)
            close()
            moveToRelative(-3f, -0.5f)
            curveTo(3f, 14.12f, 4.12f, 13f, 5.5f, 13f)
            horizontalLineToRelative(3f)
            curveToRelative(1.38f, 0f, 2.5f, 1.12f, 2.5f, 2.5f)
            verticalLineToRelative(3f)
            curveToRelative(0f, 1.38f, -1.12f, 2.5f, -2.5f, 2.5f)
            horizontalLineToRelative(-3f)
            curveTo(4.12f, 21f, 3f, 19.88f, 3f, 18.5f)
            verticalLineToRelative(-3f)
            close()
            moveTo(5.5f, 15f)
            curveTo(5.224f, 15f, 5f, 15.224f, 5f, 15.5f)
            verticalLineToRelative(3f)
            curveTo(5f, 18.776f, 5.224f, 19f, 5.5f, 19f)
            horizontalLineToRelative(3f)
            curveTo(8.776f, 19f, 9f, 18.776f, 9f, 18.5f)
            verticalLineToRelative(-3f)
            curveTo(9f, 15.224f, 8.776f, 15f, 8.5f, 15f)
            horizontalLineToRelative(-3f)
            close()
            moveTo(18f, 6f)
            horizontalLineToRelative(-2f)
            verticalLineToRelative(2f)
            horizontalLineToRelative(2f)
            verticalLineTo(6f)
            close()
            moveToRelative(-2.5f, -3f)
            curveTo(14.12f, 3f, 13f, 4.12f, 13f, 5.5f)
            verticalLineToRelative(3f)
            curveToRelative(0f, 1.38f, 1.12f, 2.5f, 2.5f, 2.5f)
            horizontalLineToRelative(3f)
            curveToRelative(1.38f, 0f, 2.5f, -1.12f, 2.5f, -2.5f)
            verticalLineToRelative(-3f)
            curveTo(21f, 4.12f, 19.88f, 3f, 18.5f, 3f)
            horizontalLineToRelative(-3f)
            close()
            moveTo(15f, 5.5f)
            curveTo(15f, 5.224f, 15.224f, 5f, 15.5f, 5f)
            horizontalLineToRelative(3f)
            curveTo(18.776f, 5f, 19f, 5.224f, 19f, 5.5f)
            verticalLineToRelative(3f)
            curveTo(19f, 8.776f, 18.776f, 9f, 18.5f, 9f)
            horizontalLineToRelative(-3f)
            curveTo(15.224f, 9f, 15f, 8.776f, 15f, 8.5f)
            verticalLineToRelative(-3f)
            close()
            moveTo(13f, 13f)
            horizontalLineToRelative(2.75f)
            verticalLineToRelative(2.75f)
            horizontalLineTo(13f)
            verticalLineTo(13f)
            close()
            moveToRelative(5.25f, 2.75f)
            horizontalLineToRelative(-2.5f)
            verticalLineToRelative(2.5f)
            horizontalLineTo(13f)
            verticalLineTo(21f)
            horizontalLineToRelative(2.75f)
            verticalLineToRelative(-2.75f)
            horizontalLineToRelative(2.5f)
            verticalLineTo(21f)
            horizontalLineTo(21f)
            verticalLineToRelative(-2.75f)
            horizontalLineToRelative(-2.75f)
            verticalLineToRelative(-2.5f)
            close()
            moveToRelative(0f, 0f)
            verticalLineTo(13f)
            horizontalLineTo(21f)
            verticalLineToRelative(2.75f)
            horizontalLineToRelative(-2.75f)
            close()
        }
    }.build()
}
